name: release

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      uses: ./.github/actions/build
    - if: startsWith(github.ref, 'refs/tags/v')
      run: |
        npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_AUTH_TOKEN}}
        npm publish --access public --tolerate-republish