name: release

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: yarn
    - run: yarn build
    - if: startsWith(github.ref, 'refs/tags/v')
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        registry: https://npm.pkg.github.com